const images = [
    {url: 'images/webp/gals/big-small.webp', alt: 'bud vase with cosmos and a white flower'},
    {url: 'images/webp/gals/basket.webp', alt: ''},
    {url: 'images/webp/gals/meadow.webp', alt: ''},
    {url: 'images/webp/gals/snowdrop.webp', alt: ''},
    {url: 'images/webp/gals/rose-crop.webp', alt: ''},
    {url: 'images/webp/gals/small-pot.webp', alt: ''},
    {url: 'images/webp/gals/whites-close.webp', alt: ''},
    {url: 'images/webp/gals/flower-bowl-flipped.webp', alt: ''},
    {url: 'images/webp/gals/tulips.webp', alt: ''},
    {url: 'images/webp/gals/urn large.webp', alt: ''},
    {url: 'images/webp/gals/flowers.webp', alt: ''},
    {url: 'images/webp/gals/cosmos2.webp', alt: ''},
    {url: 'images/webp/gals/IMG_9370.webp', alt: ''},
    {url: 'images/webp/gals/ladder.webp', alt: ''},
    {url: 'images/webp/gals/IMG_7517.webp', alt: ''},
    {url: 'images/webp/gals/stool.webp', alt: ''},
    {url: 'images/webp/gals/sb-park.webp', alt: ''},
    {url: 'images/webp/gals/urn-crop.webp', alt: ''},
    {url: 'images/webp/gals/IMG_9228.webp', alt: ''},
    {url: 'images/webp/gals/dahlia-pot.webp', alt: ''},
    {url: 'images/webp/gals/pink.webp', alt: ''},
    {url: 'images/webp/gals/flowerpot.webp', alt: ''},
    {url: 'images/webp/gals/IMG_8759.webp', alt: ''},
    {url: 'images/webp/gals/lilac.webp', alt: ''},
    {url: 'images/webp/gals/IMG_6845.webp', alt: ''},
    {url: 'images/webp/gals/daisys.webp', alt: ''},
    {url: 'images/webp/gals/IMG_7585.webp', alt: ''},
    {url: 'images/webp/gals/wreath-snow-s.webp', alt: ''},
    {url: 'images/webp/gals/IMG_9400.webp', alt: ''},
    {url: 'images/webp/gals/gyp.webp', alt: ''},
    {url: 'images/webp/gals/IMG_9795.webp', alt: ''},
    {url: 'images/webp/gals/IMG_8187.webp', alt: ''},
    {url: 'images/webp/gals/IMG_9675.webp', alt: ''},
    {url: 'images/webp/gals/IMG_7327.webp', alt: ''},
    {url: 'images/webp/gals/IMG_8600.webp', alt: ''},
    {url: 'images/webp/gals/img_5407.webp', alt: ''},
    {url: 'images/webp/gals/bunch.webp', alt: ''}
]

export default images
